from distutils.core import setup
setup(
  name='codetimer',
  packages=['codetimer'],
  version='1.0.0',
  license='MIT',
  description='Custom timer for your Python coding pleasure',
  author='Stephen Gemin',
  author_email='s.gemin88@gmail.com',
  url='https://github.com/StephenGemin/codetimer',
  download_url='https://github.com/StephenGemin/codetimer/archive/1.0.0.tar.gz',
  keywords=["decorator", "decorators", "code timer", "timing",
            "code timing", "context manager"],
  classifiers=[
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Developers',
    'Topic :: Software Development :: Build Tools',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3.3',
    'Programming Language :: Python :: 3.4',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
  ],
)

settings.update(
    name='codetimer',
    packages=['codetimer'],
    version='1.0.0',
    description='Custom timer for your Python coding pleasure',
    author='Stephen Gemin',
    download_url='https://github.com/StephenGemin/codetimer/archive/1.0.0.tar.gz',
    author_email='s.gemin88@gmail.com',
    license='MIT',
    url='https://github.com/rholder/retrying',
    classifiers=CLASSIFIERS,
    keywords="decorator decorators code timer timing context manager",
)
