# Python CircleCI 2.0 configuration file
version: 2.1
jobs:
  build_test:
    docker:
      - image: circleci/python:3.6
      - image: circleci/python:3.7
      - image: circleci/python:3.8
      - image: circleci/python:3.9
    steps:
      - checkout  # Step 1: obtain repo from GitHub
      - run:  # Step 2: create virtual env and install dependencies
          name: install dependencies
          command: |
            python setup.py sdist bdist_wheel
            pip install dist/code_timer-1.1.6-py3-none-any.whl
            pip install -r requirements_dev.txt
      - run:  # Step 3: run tests
          name: run tests
          command: |
            pytest -v --cov=tests/

#  test_pypi_publish:
#    docker:
#      - image: circleci/python:3.8
#    steps:
#      - checkout  # checkout source code to working directory
#      - run:
#          name: test pypi publish
#          command: |  # create whl, install twine and publish to Test PyPI
#            python setup.py sdist bdist_wheel
#            pip install twine
#            twine upload --repository testpypi dist/*
  pypi_publish:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout  # checkout source code to working directory
      - run:
          name: real pypi publish
          command: |  # create whl, install twine and publish to Test PyPI
            python setup.py sdist bdist_wheel
            pip install twine
            twine upload dist/*

workflows:
  build_test_publish:
    jobs:
      - build_test
#      - test_pypi_publish:
#          requires:
#            - build_test
#          filters:
#            branches:
#              only:
#                - master
      - pypi_publish:
          requires:
            - build_test
          filters:
            branches:
              only:
                - master